name: docker-pipeline
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: dora-backend:latest
          outputs: type=docker, dest=/tmp/dora-backend.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dora-backend
          path: /tmp/dora-backend.tar

  compose:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dora-backend
          path: /tmp
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Load image
        run: |
          docker load --input /tmp/dora-backend.tar
          docker image ls -a
      - name: Docker Compose Config
        run: |
          docker compose config -o docker-compose-filled.yml
      - name: Run Docker Compose
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: docker-compose-filled.yml
          up-flags: "--detach"
          down-flags: "--timeout 30"
      - name: Check Running Containers
        run: |
          docker ps -a
